Project: Testing Practice
taiwocoker/Testing-practice-with-jest pull request #1
Opened 2020-09-10 17:01 UTC by taiwocoker

Dear TSE,

We wrote modules for analyze, CeaserSipher, Calculator, reverse string, and Capitalize functions and wrote tests for each of them using jest. 
Thanks for reviewing.

2020-09-10 19:01 UTC, uryelah requested changes
Hi **Patricia Manezeu & Taiwo Coker**, I'm Sarah your reviewer for this PR 👩‍🚀 

You did a great job with this project! I loved how you also tested for errors!
There's just one issue with the README to fix and then you'll be free to write more awesome tests in your next projects.

# Required Changes 🏗️ 🐛 💡

- [ ] Please complete the README instructions for running tests.

- [ ] [OPTIONAL] I strongly recommend Please put the tests in a specific spec or tests folder. they should not be in the same folder as the functions.

(Check the comments below too)

-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-09-10 19:01 UTC, uryelah commented on README.md
- [x] Please add instructions on how to run the code and how to run the tests locally, that inclues all the necessary setup, instalations, and terminal commands.

2020-09-10 19:01 UTC, uryelah commented on src/analyse.js
> +    average: array.reduce((a, b) => a + b, 0) / array.length,
- [x] [OPTIONAL] What happens if the length of the array is 0? Can you handle that error?

2020-09-10 19:01 UTC, uryelah commented on src/analyse.js
> +function analyse(array) {
- [x] Let's use ES6 arrow function expressions whenever possible instead of the `function` keyword.
Ex:
```
const analyse = array => {
...
}
```

2020-09-10 19:01 UTC, uryelah commented on src/analyse.test.js
> +test('should have average', () => {
- [x] [OPTIONAL] You could add a test also for empty arrays or for when the type of the argument is not array.

2020-09-10 19:01 UTC, uryelah commented on src/calculator.js
> +function Calculator(a, b) {
- [x] Prefer arrow functions (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) for this and it's methods.

2020-09-10 19:01 UTC, uryelah commented on src/capitalize.js
> +    const arr = string.split('');
- [x] [OPTIONAL] No need to split the string into an array. You can just get the first element using brackets as you would in arrays and concatenate it with .substring.

More:
https://www.w3schools.com/jsref/jsref_substring.asp

2020-09-10 19:01 UTC, uryelah commented on src/capitalize.test.js
> +  expect(capitalize('bread')).toBe('Bread');
- [x] [OPTIONAL] It would be a good idea to test this with more than one valid string. Otherwise you can't really be sure it will work properly in every string. Try to have more than one test case.

2020-09-10 19:01 UTC, uryelah commented on src/cs_encryption.js
> +  const alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
- [ ] [OPTIONAL] If you store the alphabet inside an object with the letters as keys and the indexes as values, ex: `a: 0`, the look up time would be faster. 

Using array.include and array.indexOf can slow down your code.

2020-09-10 19:01 UTC, uryelah commented on src/cs_encryption.js
> +    const arr = string.split('');
- [x] [OPTIONAL] No need to turn the string into an array, you can loop a string using its iterator with the `for of` loop.

More: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

2020-09-10 19:01 UTC, uryelah commented on src/reverse_string.test.js
> +test('reverseString hello to return olleh', () => {
- [x] [OPTIONAL] Remeber to add more than one valid test case.

2020-09-11 08:13 UTC, patriciachrysy commented
Applied all of the mandatory requested changes and some of the optional ones. Thanks for reviewing again.

2020-09-11 10:00 UTC, rOluochKe approved these changes
### You got it right, well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy hacking!

2020-09-11 15:34 UTC, merged